[package]
name = "Torrent_API"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
futures = "0.3.31"
reqwest = "0.12.12"
serde = "1.0.217"
thirtyfour = "0.35.0"
tokio = "1.43.0"
undetected-chromedriver = "0.1.2"
